# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tA0F0bLk1OjxN1EAmqPpa4-LuNCCwA1w
"""

import streamlit as st
from main import predict_cluster

st.set_page_config(
    page_title="FIFA Player Cluster Prediction",
    page_icon="⚽",
    layout="centered"
)

st.title("⚽ FIFA Player Clustering")
st.write("Enter player attributes to find the cluster.")

pace = st.number_input("Pace", min_value=0.0, max_value=100.0, value=70.0)
shooting = st.number_input("Shooting", min_value=0.0, max_value=100.0, value=70.0)
passing = st.number_input("Passing", min_value=0.0, max_value=100.0, value=70.0)
dribbling = st.number_input("Dribbling", min_value=0.0, max_value=100.0, value=70.0)
defending = st.number_input("Defending", min_value=0.0, max_value=100.0, value=70.0)
physic = st.number_input("Physic", min_value=0.0, max_value=100.0, value=70.0)

if st.button("Predict Cluster"):

    result = predict_cluster(
        pace,
        shooting,
        passing,
        dribbling,
        defending,
        physic
    )

    st.success(f"Predicted Cluster: {result}")

    if result == 0:
        st.info("Cluster 0: Player belongs to Group 0")
    elif result == 1:
        st.info("Cluster 1: Player belongs to Group 1")
    else:
        st.info("Cluster 2: Player belongs to Group 2")