# -*- coding: utf-8 -*-
"""check_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjqOu_Exl71TSESdwDcqmo9UPQ1nQfKG
"""

import pickle

model = pickle.load(open("fifa_kmeans_pipeline.pkl22", "rb"))

print(type(model))

if hasattr(model, "feature_names_in_"):
    print(model.feature_names_in_)
else:
    print("No feature_names_in_ found")

if hasattr(model, "named_steps"):
    print("Pipeline steps:")
    print(model.named_steps)