# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQrLw7cQl3mAcpzsmMoZslTkk3STPQwi
"""

import pickle
import pandas as pd

# Load model
model = pickle.load(open("fifa_kmeans_pipeline.pkl", "rb"))

def predict_cluster(pace, shooting, passing, dribbling, defending, physic):

    data = pd.DataFrame({
        "pace": [pace],
        "shooting": [shooting],
        "passing": [passing],
        "dribbling": [dribbling],
        "defending": [defending],
        "physic": [physic]
    })

    cluster = model.predict(data)[0]

    return int(cluster)